version: "3"
services:
  postgres:
    container_name: postgres
    image: postgres:16.0
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vktest
    ports:
      - "5432:5432"

  backend:
    container_name: backend
    image: backend
    build:
      context: .
    environment:
      - DATABASE_URL=jdbc:postgresql://postgres:5432/vktest
    depends_on:
      postgres:
        condition: service_started
    ports:
      - "8080:8080"
